const db = require('../firebase/firestoreService');

const productMap = {
  "Zeera": "Aisle1",
  "Haldi": "Aisle1",
  "Laal Mirch": "Aisle1",
  "Basmati Rice": "Aisle2",
  "Masoor Dal": "Aisle2",
  "Chana Dal": "Aisle2",
  "Cornflakes": "Aisle3",
  "Paratha": "Aisle3",
  "Bread": "Aisle3",
  "White Sugar": "Aisle4",
  "Brown Sugar": "Aisle4",
  "Honey": "Aisle4",
  "Macaroni": "Aisle5",
  "Spaghetti": "Aisle5",
  "Instant Noodles": "Aisle5",
  "Shampoo": "Aisle6",
  "Toothpaste": "Aisle6",
  "Soap": "Aisle6",
  "Floor Cleaner": "Aisle7",
  "Toilet Cleaner": "Aisle7",
  "Dish Soap": "Aisle7",
  "Tomato Ketchup": "Aisle8",
  "Imli Chutney": "Aisle8",
  "Green Chutney": "Aisle8",
  "Cooking Oil": "Aisle9",
  "Ghee": "Aisle9",
  "Olive Oil": "Aisle9",
  "Tea Bags": "Aisle10",
  "Green Tea": "Aisle10",
  "Instant Coffee": "Aisle10",
  "Chips": "Aisle11",
  "Nimco": "Aisle11",
  "Chocolate": "Aisle11",
  "Dog Food": "Aisle12",
  "Cat Food": "Aisle12",
  "Bird Seeds": "Aisle12",
  "Diapers": "Aisle13",
  "Baby Lotion": "Aisle13",
  "Baby Shampoo": "Aisle13",
  "Toilet Paper": "Aisle14",
  "Tissue Box": "Aisle14",
  "Paper Towels": "Aisle14",
  "Apple": "Aisle15",
  "Potato": "Aisle15",
  "Carrot": "Aisle15",
  "Bun": "Aisle16",
  "Cake": "Aisle16",
  "Croissant": "Aisle16",
  "Chicken": "Aisle17",
  "Mutton": "Aisle17",
  "Beef": "Aisle17",
  "Shrimp": "Aisle18",
  "Rohu Fish": "Aisle18",
  "Crab": "Aisle18",
  "Frozen Paratha": "Aisle19",
  "Frozen Nuggets": "Aisle19",
  "Frozen Fries": "Aisle19",
  "Cola": "Aisle20",
  "Juice": "Aisle20",
  "Energy Drink": "Aisle20",
  "Zeera 1": "Aisle1",
  "Haldi 1": "Aisle1",
  "Laal Mirch 1": "Aisle1",
  "Basmati Rice 1": "Aisle2",
  "Masoor Dal 1": "Aisle2",
  "Chana Dal 1": "Aisle2",
  "Cornflakes 1": "Aisle3",
  "Paratha 1": "Aisle3",
  "Bread 1": "Aisle3",
  "White Sugar 1": "Aisle4",
  "Brown Sugar 1": "Aisle4",
  "Honey 1": "Aisle4",
  "Macaroni 1": "Aisle5",
  "Spaghetti 1": "Aisle5",
  "Instant Noodles 1": "Aisle5",
  "Shampoo 1": "Aisle6",
  "Toothpaste 1": "Aisle6",
  "Soap 1": "Aisle6",
  "Floor Cleaner 1": "Aisle7",
  "Toilet Cleaner 1": "Aisle7",
  "Dish Soap 1": "Aisle7",
  "Tomato Ketchup 1": "Aisle8",
  "Imli Chutney 1": "Aisle8",
  "Green Chutney 1": "Aisle8",
  "Cooking Oil 1": "Aisle9",
  "Ghee 1": "Aisle9",
  "Olive Oil 1": "Aisle9",
  "Tea Bags 1": "Aisle10",
  "Green Tea 1": "Aisle10",
  "Instant Coffee 1": "Aisle10",
  "Chips 1": "Aisle11",
  "Nimco 1": "Aisle11",
  "Chocolate 1": "Aisle11",
  "Dog Food 1": "Aisle12",
  "Cat Food 1": "Aisle12",
  "Bird Seeds 1": "Aisle12",
  "Diapers 1": "Aisle13",
  "Baby Lotion 1": "Aisle13",
  "Baby Shampoo 1": "Aisle13",
  "Toilet Paper 1": "Aisle14",
  "Tissue Box 1": "Aisle14",
  "Paper Towels 1": "Aisle14",
  "Apple 1": "Aisle15",
  "Potato 1": "Aisle15",
  "Carrot 1": "Aisle15",
  "Bun 1": "Aisle16",
  "Cake 1": "Aisle16",
  "Croissant 1": "Aisle16",
  "Chicken 1": "Aisle17",
  "Mutton 1": "Aisle17",
  "Beef 1": "Aisle17",
  "Shrimp 1": "Aisle18",
  "Rohu Fish 1": "Aisle18",
  "Crab 1": "Aisle18",
  "Frozen Paratha 1": "Aisle19",
  "Frozen Nuggets 1": "Aisle19",
  "Frozen Fries 1": "Aisle19",
  "Cola 1": "Aisle20",
  "Juice 1": "Aisle20",
  "Energy Drink 1": "Aisle20",
  "Zeera 2": "Aisle1",
  "Haldi 2": "Aisle1",
  "Laal Mirch 2": "Aisle1",
  "Basmati Rice 2": "Aisle2",
  "Masoor Dal 2": "Aisle2",
  "Chana Dal 2": "Aisle2",
  "Cornflakes 2": "Aisle3",
  "Paratha 2": "Aisle3",
  "Bread 2": "Aisle3",
  "White Sugar 2": "Aisle4",
  "Brown Sugar 2": "Aisle4",
  "Honey 2": "Aisle4",
  "Macaroni 2": "Aisle5",
  "Spaghetti 2": "Aisle5",
  "Instant Noodles 2": "Aisle5",
  "Shampoo 2": "Aisle6",
  "Toothpaste 2": "Aisle6",
  "Soap 2": "Aisle6",
  "Floor Cleaner 2": "Aisle7",
  "Toilet Cleaner 2": "Aisle7",
  "Dish Soap 2": "Aisle7",
  "Tomato Ketchup 2": "Aisle8",
  "Imli Chutney 2": "Aisle8",
  "Green Chutney 2": "Aisle8",
  "Cooking Oil 2": "Aisle9",
  "Ghee 2": "Aisle9",
  "Olive Oil 2": "Aisle9",
  "Tea Bags 2": "Aisle10",
  "Green Tea 2": "Aisle10",
  "Instant Coffee 2": "Aisle10",
  "Chips 2": "Aisle11",
  "Nimco 2": "Aisle11",
  "Chocolate 2": "Aisle11",
  "Dog Food 2": "Aisle12",
  "Cat Food 2": "Aisle12",
  "Bird Seeds 2": "Aisle12",
  "Diapers 2": "Aisle13",
  "Baby Lotion 2": "Aisle13",
  "Baby Shampoo 2": "Aisle13",
  "Toilet Paper 2": "Aisle14",
  "Tissue Box 2": "Aisle14",
  "Paper Towels 2": "Aisle14",
  "Apple 2": "Aisle15",
  "Potato 2": "Aisle15",
  "Carrot 2": "Aisle15",
  "Bun 2": "Aisle16",
  "Cake 2": "Aisle16",
  "Croissant 2": "Aisle16",
  "Chicken 2": "Aisle17",
  "Mutton 2": "Aisle17",
  "Beef 2": "Aisle17",
  "Shrimp 2": "Aisle18",
  "Rohu Fish 2": "Aisle18",
  "Crab 2": "Aisle18",
  "Frozen Paratha 2": "Aisle19",
  "Frozen Nuggets 2": "Aisle19",
  "Frozen Fries 2": "Aisle19",
  "Cola 2": "Aisle20",
  "Juice 2": "Aisle20",
  "Energy Drink 2": "Aisle20",
  "Zeera 3": "Aisle1",
  "Haldi 3": "Aisle1",
  "Laal Mirch 3": "Aisle1",
  "Basmati Rice 3": "Aisle2",
  "Masoor Dal 3": "Aisle2",
  "Chana Dal 3": "Aisle2",
  "Cornflakes 3": "Aisle3",
  "Paratha 3": "Aisle3",
  "Bread 3": "Aisle3",
  "White Sugar 3": "Aisle4",
  "Brown Sugar 3": "Aisle4",
  "Honey 3": "Aisle4",
  "Macaroni 3": "Aisle5",
  "Spaghetti 3": "Aisle5",
  "Instant Noodles 3": "Aisle5",
  "Shampoo 3": "Aisle6",
  "Toothpaste 3": "Aisle6",
  "Soap 3": "Aisle6",
  "Floor Cleaner 3": "Aisle7",
  "Toilet Cleaner 3": "Aisle7",
  "Dish Soap 3": "Aisle7",
  "Tomato Ketchup 3": "Aisle8",
  "Imli Chutney 3": "Aisle8",
  "Green Chutney 3": "Aisle8",
  "Cooking Oil 3": "Aisle9",
  "Ghee 3": "Aisle9",
  "Olive Oil 3": "Aisle9",
  "Tea Bags 3": "Aisle10",
  "Green Tea 3": "Aisle10",
  "Instant Coffee 3": "Aisle10",
  "Chips 3": "Aisle11",
  "Nimco 3": "Aisle11",
  "Chocolate 3": "Aisle11",
  "Dog Food 3": "Aisle12",
  "Cat Food 3": "Aisle12",
  "Bird Seeds 3": "Aisle12",
  "Diapers 3": "Aisle13",
  "Baby Lotion 3": "Aisle13",
  "Baby Shampoo 3": "Aisle13",
  "Toilet Paper 3": "Aisle14",
  "Tissue Box 3": "Aisle14",
  "Paper Towels 3": "Aisle14",
  "Apple 3": "Aisle15",
  "Potato 3": "Aisle15",
  "Carrot 3": "Aisle15",
  "Bun 3": "Aisle16",
  "Cake 3": "Aisle16",
  "Croissant 3": "Aisle16",
  "Chicken 3": "Aisle17",
  "Mutton 3": "Aisle17",
  "Beef 3": "Aisle17",
  "Shrimp 3": "Aisle18",
  "Rohu Fish 3": "Aisle18",
  "Crab 3": "Aisle18",
  "Frozen Paratha 3": "Aisle19",
  "Frozen Nuggets 3": "Aisle19",
  "Frozen Fries 3": "Aisle19",
  "Cola 3": "Aisle20",
  "Juice 3": "Aisle20",
  "Energy Drink 3": "Aisle20",
  "Zeera 4": "Aisle1",
  "Haldi 4": "Aisle1",
  "Laal Mirch 4": "Aisle1",
  "Basmati Rice 4": "Aisle2",
  "Masoor Dal 4": "Aisle2",
  "Chana Dal 4": "Aisle2",
  "Cornflakes 4": "Aisle3",
  "Paratha 4": "Aisle3",
  "Bread 4": "Aisle3",
  "White Sugar 4": "Aisle4",
  "Brown Sugar 4": "Aisle4",
  "Honey 4": "Aisle4",
  "Macaroni 4": "Aisle5",
  "Spaghetti 4": "Aisle5",
  "Instant Noodles 4": "Aisle5",
  "Shampoo 4": "Aisle6",
  "Toothpaste 4": "Aisle6",
  "Soap 4": "Aisle6",
  "Floor Cleaner 4": "Aisle7",
  "Toilet Cleaner 4": "Aisle7",
  "Dish Soap 4": "Aisle7",
  "Tomato Ketchup 4": "Aisle8",
  "Imli Chutney 4": "Aisle8",
  "Green Chutney 4": "Aisle8",
  "Cooking Oil 4": "Aisle9",
  "Ghee 4": "Aisle9",
  "Olive Oil 4": "Aisle9",
  "Tea Bags 4": "Aisle10",
  "Green Tea 4": "Aisle10",
  "Instant Coffee 4": "Aisle10",
  "Chips 4": "Aisle11",
  "Nimco 4": "Aisle11",
  "Chocolate 4": "Aisle11",
  "Dog Food 4": "Aisle12",
  "Cat Food 4": "Aisle12",
  "Bird Seeds 4": "Aisle12",
  "Diapers 4": "Aisle13",
  "Baby Lotion 4": "Aisle13",
  "Baby Shampoo 4": "Aisle13",
  "Toilet Paper 4": "Aisle14",
  "Tissue Box 4": "Aisle14",
  "Paper Towels 4": "Aisle14",
  "Apple 4": "Aisle15",
  "Potato 4": "Aisle15",
  "Carrot 4": "Aisle15",
  "Bun 4": "Aisle16",
  "Cake 4": "Aisle16",
  "Croissant 4": "Aisle16",
  "Chicken 4": "Aisle17",
  "Mutton 4": "Aisle17",
  "Beef 4": "Aisle17",
  "Shrimp 4": "Aisle18",
  "Rohu Fish 4": "Aisle18",
  "Crab 4": "Aisle18",
  "Frozen Paratha 4": "Aisle19",
  "Frozen Nuggets 4": "Aisle19",
  "Frozen Fries 4": "Aisle19",
  "Cola 4": "Aisle20",
  "Juice 4": "Aisle20",
  "Energy Drink 4": "Aisle20"
};

async function seed() {
  try {
    const ref = db.collection('storeMaps').doc('demoStore');
    await ref.set({ productToAisleMap: productMap }, { merge: true });
    console.log('✅ Seeded expanded map to Firestore');
  } catch (error) {
    console.error('❌ Error seeding data:', error.message);
    console.log('💡 Make sure Firestore database is created in your Firebase project');
    console.log('💡 Visit: https://console.firebase.google.com/project/viaregrocery/firestore');
  }
}

seed().then(() => process.exit()).catch((error) => {
  console.error('❌ Script failed:', error.message);
  process.exit(1);
});
